site_name: Методические рекомендации по лабораторным работам по дисциплине "Оптимизация веб-приложений" 

theme:
  name: material
  language: ru
  features:
    - content.code.copy     # кнопка "копировать"
    - content.image.zoom    # zoom картинок
    - navigation.top        # "наверх"
    - navigation.tracking   # подсветка активного пункта в правом TOC
    - toc.follow            # правый TOC следует за прокруткой
nav:
  
    - Лабораторные работы: 
      - Лабораторная работа №1: index.md
      - Лабораторная работа №2: lab2.md
      - Лабораторная работа №3: lab3.md
      - Лабораторная работа №4: lab4.md
      - Лабораторная работа №5: lab5.md
      - Лабораторная работа №6: lab6.md
      - Лабораторная работа №7: lab7.md
      - Лабораторная работа №8: lab8.md
      - Лабораторная работа №9: lab9.md
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

extra_css:
  - stylesheets/extra.css